### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by step21** [rhdunn/cainteoir-gtk#25]
Hi, is this and cainteoir-engine still active? Or would you recommend to just use espeak instead?
Just asking as there doesn't seem to be that much activity here and the ppa hasn't been updated in forever.

**Comment by rhdunn** [comment]
Hi,

I use cainteoir-gtk personally all the time, so in that sense cainteoir-engine and cainteoir-gtk are still active and should work with the different versions of espeak. With my efforts now focused on maintaining and enhancing espeak via the espeak-ng project, I don't have the time to add new features to cainteoir-engine as well.

My current thinking is to keep cainteoir-gtk as a text-to-speech document reader application, but to remove its dependence from cainteoir-engine. The cainteoir-editor part of cainteoir-gtk (currently a waveform visualizer), will be moved to the tts-dev-studio project.

For cainteoir-engine itself, my current thinking is to split out the phoneme logic into a separate library. The audio recording (wav, ogg) I want to move into the pcaudiolib project, so it can be used by espeak and other projects. The dictionary management will be part of tts-dev-studio, and will likely just support cmudict and espeak style dictionaries. The language data has been moved to the bcp47-data project, and I will likely spin off a project to parse that data and generate the RDF output from that data. I'm not sure about the other parts of cainteoir-engine.

**Comment by step21** [comment]
Thanks for the detailed reply. I had installed both from source now, but was actually wondering what cainteoir engine was used for as the speech engine seems to be espeak or pico.
